#spring.threads.virtual.enabled=true
spring.application.name=document-server
spring.profiles.active=dev

#spring.config.import=optional:configserver:http://config-server:8888?fail-fast=true&max-attempts=10&max-interval=1500&multiplier=1.2&initial-interval=1100
#management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans
server.port=8083

upload_directory=/app/data

spring.r2dbc.url=r2dbc:postgresql://localhost:5432/mydb
spring.r2dbc.username=myuser
spring.r2dbc.password=mypassword

# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.format_sql=true
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

eureka.client.preferIpAddress=true
eureka.client.registerWithEureka=true
eureka.client.fetchRegistry=true
eureka.client.serviceUrl.defaultZone=http://discovery-server1:8761/eureka,http://discovery-server2:8762/eureka,http://discovery-server3:8763/eureka

management.endpoints.web.exposure.include=*
management.health.enabled=true
management.health.show-details=always
management.health.show-components=always
management.tracing.sampling.probability=1.0

# FUNÇÕES
spring.cloud.function.definition=processor

# RABBIT
#spring.rabbitmq.host=localhost
#spring.rabbitmq.port=5672
#spring.rabbitmq.username=guest
#spring.rabbitmq.password=guest

# BINDINGS
spring.cloud.stream.bindings.processor-in-0.destination=report.content-generated
spring.cloud.stream.bindings.processor-in-0.group=document-server-processor

spring.cloud.stream.bindings.processor-out-0.destination=report.document-created

# KAFKA
spring.cloud.stream.kafka.binder.producer-properties.key.serializer=org.apache.kafka.common.serialization.StringSerializer
spring.cloud.stream.kafka.binder.brokers=localhost:9092
